apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ecr_url/image:tag
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"

            - name: PORT
              value: "8080"

          envFrom:
            - secretRef:
                name: cognito-secrets

